// File generated by FlutterFire CLI — reconstructed from GoogleService-Info.plist
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLSe8l9Y1QnPQLlsfN7LtrlZeYR-MgKo',
    appId: '1:771678564230:android:91ac94a950914b63f78607',
    messagingSenderId: '771678564230',
    projectId: 'p2pchatapp-c16b8',
    storageBucket: 'p2pchatapp-c16b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLSe8l9Y1QnPQLlsfN7LtrlZeYR-MgKo',
    appId: '1:771678564230:ios:4b63525419cb5f81f78607',
    messagingSenderId: '771678564230',
    projectId: 'p2pchatapp-c16b8',
    storageBucket: 'p2pchatapp-c16b8.firebasestorage.app',
    iosClientId: '771678564230-i81kr16cq8rhs01p9mjvl8vmtuogqok7.apps.googleusercontent.com',
    iosBundleId: 'io.peerlink.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLSe8l9Y1QnPQLlsfN7LtrlZeYR-MgKo',
    appId: '1:771678564230:ios:4b63525419cb5f81f78607',
    messagingSenderId: '771678564230',
    projectId: 'p2pchatapp-c16b8',
    storageBucket: 'p2pchatapp-c16b8.firebasestorage.app',
    iosClientId: '771678564230-i81kr16cq8rhs01p9mjvl8vmtuogqok7.apps.googleusercontent.com',
    iosBundleId: 'io.peerlink.chat',
  );
}
